# -------------------------------------------------
# Site settings
# -------------------------------------------------

title: ""
email: mail@ils.uni-stuttgart.de

description: >-
  ILS Doctoral Seminar 2026

baseurl: "/"
url: "https://ils-stuttgart.github.io"

# -------------------------------------------------
# Social links
# -------------------------------------------------

github_username: ils-stuttgart

linkedin_url: "https://www.linkedin.com/company/universit%C3%A4t-stuttgart-institut-f%C3%BCr-luftfahrtsysteme-ils/"

# -------------------------------------------------
# Build settings
# -------------------------------------------------

theme: minima

minima:
  custom_css:
    - /assets/css/ils.css

plugins:
  - jekyll-feed

# -------------------------------------------------
# Collections
# -------------------------------------------------

collections:
  abstracts:
    output: true
    permalink: /seminar-2026/abstracts/:name/
    hide: true
